### ISSUE TITLE
登录后报错

### ISSUE THREAD

**Issue by yunxinlxsy** [Jonariguez/Spider_JingdongTry#14]

**Comment by yunxinlxsy** [comment]
> ![chrome_2019-08-13_12-24-58](https://user-images.githubusercontent.com/22430344/62915062-98b95300-bdc5-11e9-8a95-6587c451df77.png)
> 怎么解决呀，文字信息如下
> 
> DevTools listening on ws://127.0.0.1:59409/devtools/browser/2448a918-ac28-4011-9497-a70bc01351af
> F:\computer soft\jd_try_py_github\Spider_JingdongTry-master\Method_First\Try_selenium.py:21: DeprecationWarning: use options instead of chrome_options
> browser = webdriver.Chrome(chrome_options=chrome_options)
> 
> DevTools listening on ws://127.0.0.1:59426/devtools/browser/83ebd4c6-a2ab-4e80-b2ec-3a9e4b6baabb
> [33588:15660:0813/122233.305:ERROR:browser_process_sub_thread.cc(203)] Waited 84 ms for network service
> [0813/122237.614:INFO:CONSOLE(539)] "Mixed Content: The page at 'https://www.jd.com/' was loaded over HTTPS, but requested an insecure image 'http://m.360buyimg.com/babel/jfs/t1/45423/33/385/778/5cd4f265E442a9342/0aff0a42cece09ee.png'. This content should also be served over HTTPS.", source: https://www.jd.com/ (539)
> [0813/122237.615:INFO:CONSOLE(590)] "Mixed Content: The page at 'https://www.jd.com/' was loaded over HTTPS, but requested an insecure image 'http://m.360buyimg.com/babel/jfs/t1/39418/35/2029/3048/5cbf06bbE9a6e2beb/6a9b204b0a4cc3d0.png'. This content should also be served over HTTPS.", source: https://www.jd.com/ (590)
> [0813/122237.616:INFO:CONSOLE(604)] "Mixed Content: The page at 'https://www.jd.com/' was loaded over HTTPS, but requested an insecure image 'http://m.360buyimg.com/babel/jfs/t1/31847/11/14820/1581/5cbf09bdE07a1e79c/1281c9340ef15c3e.png'. This content should also be served over HTTPS.", source: https://www.jd.com/ (604)
> [0813/122237.616:INFO:CONSOLE(618)] "Mixed Content: The page at 'https://www.jd.com/' was loaded over HTTPS, but requested an insecure image 'http://m.360buyimg.com/babel/jfs/t1/33078/37/6694/1685/5cbf09d0E5cea6165/693857001bfb3b17.png'. This content should also be served over HTTPS.", source: https://www.jd.com/ (618)
> [0813/122237.616:INFO:CONSOLE(632)] "Mixed Content: The page at 'https://www.jd.com/' was loaded over HTTPS, but requested an insecure image 'http://m.360buyimg.com/babel/jfs/t1/35979/1/3099/3447/5cbf09e4E90c0b4f4/e632d50688935da6.png'. This content should also be served over HTTPS.", source: https://www.jd.com/ (632)
> [0813/122237.617:INFO:CONSOLE(646)] "Mixed Content: The page at 'https://www.jd.com/' was loaded over HTTPS, but requested an insecure image 'http://m.360buyimg.com/babel/jfs/t1/35663/12/5436/1443/5cbf0a13E614f5bb0/6ab7c7eb7caa4656.png'. This content should also be served over HTTPS.", source: https://www.jd.com/ (646)
> [0813/122237.617:INFO:CONSOLE(660)] "Mixed Content: The page at 'https://www.jd.com/' was loaded over HTTPS, but requested an insecure image 'http://m.360buyimg.com/babel/jfs/t1/34018/19/6744/3066/5cbf09a9Eef05e8bd/6a08fe38fa0f8143.png'. This content should also be served over HTTPS.", source: https://www.jd.com/ (660)
> [0813/122237.618:INFO:CONSOLE(674)] "Mixed Content: The page at 'https://www.jd.com/' was loaded over HTTPS, but requested an insecure image 'http://m.360buyimg.com/babel/jfs/t1/74010/31/656/1821/5cedfd1dE574a6d39/21ed5b49bcde9067.png'. This content should also be served over HTTPS.", source: https://www.jd.com/ (674)
> [0813/122237.619:INFO:CONSOLE(688)] "Mixed Content: The page at 'https://www.jd.com/' was loaded over HTTPS, but requested an insecure image 'http://m.360buyimg.com/babel/jfs/t1/35852/40/5378/815/5cbf09f9E660e7e71/18b5679ed16e6a91.png'. This content should also be served over HTTPS.", source: https://www.jd.com/ (688)
> [0813/122237.966:INFO:CONSOLE(1)] "%c鏈〉闈㈢敱 鍑瑰嚫瀹為獙瀹わ紙JDC-澶氱粓绔爺鍙戦儴锛?璐熻矗寮€鍙戯紝浣犲彲浠ラ€氳繃 https://aotu.io 浜嗚В鎴戜滑銆?
> 
> 濡傛灉浣犲鎴戜滑鍦ㄥ仛鐨勪簨鎯呬篃鏈夊叴瓒ｏ紝娆㈣繋鍔犲叆 [aotu@jd.com](mailto:aotu@jd.com)锛堟敞鏄庢潵鑷猚onsole锛?
> 
> 鏈」鐩獎鍌茬殑浣跨敤浜?鍑瑰嚫瀹為獙瀹?鍑哄搧鐨凬erv妗嗘灦锛岀浉鍏冲唴瀹瑰強鐢熸€佷綘鍙互閫氳繃瀹樼綉浜嗚В鏇村銆?
> https://nerv.aotu.io/
> 
> ", source: https://misc.360buyimg.com/mtd/pc/index_2019/1.0.0/static/js/index.chunk.js (1)
> Traceback (most recent call last):
> File "F:\computer soft\jd_try_py_github\Spider_JingdongTry-master\Method_First\Try_selenium.py", line 180, in 
> login()
> File "F:\computer soft\jd_try_py_github\Spider_JingdongTry-master\Method_First\Try_selenium.py", line 133, in login
> browser.add_cookie(cookie)
> File "C:\Users\10638\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 894, in add_cookie
> self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
> File "C:\Users\10638\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "C:\Users\10638\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid 'expiry'
> (Session info: headless chrome=76.0.3809.100)
